#!/usr/bin/env bash
# This script contains an answer to questions about MAC addresses.
#Questions and answer choices:
#What is a MAC address?
#1.The name of a network interface
#2.The unique identifier of a network interface
#3.A network interface
answer0=2
echo $answer0

#What is an IP address?
#1. Is to devices connected to a network what postal address is to houses
#2. The unique identifier of a network interface
#3.Is a number that network devices use to connect to networks
answer1=1
echo $answer1
