#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=10
for (( i=1; i<=10; i++ ))
do  
   echo "Best School"
done
